name: Linux AppImage Build

on:
  push:
    paths-ignore:
      - '.github/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc

        configuration:
          - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: clang

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup OpenGL, SFML (Linux)
      run: |
        sudo apt install -y xorg-dev freeglut3-dev libfreetype-dev libxrandr-dev 
        sudo apt install -y libudev-dev libflac-dev libflac++-dev libvorbis-dev
        sudo apt install -y libvorbisenc2 libalut-dev

    - name: Configure (${{ matrix.configuration }})
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        mkdir -p build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..

    - name: Build with ${{ matrix.compiler }}
      run: |
        cd build
        make

    - name: Download AppImage tools
      run: |
        cd build
        wget -c "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
        chmod +x linuxdeploy-x86_64.AppImage
    
    - name: Bundle AppImage
      run: |
        cd build
        make install DESTDIR=AppDir
        ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage

    - uses: actions/upload-artifact@v3
      with:
        name: appimage
        path: build/Downpour_The_Game*.AppImage

    - name: Simple Rename
      run: |
        mv build/Downpour_The_Game*.AppImage Downpour_The_Game-x86_64.AppImage

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Downpour_The_Game-x86_64.AppImage
